roles:
  - name: community.general.pacman
    version: "12.3.0"
collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: "12.3.0"
    source: https://galaxy.ansible.com
